### ISSUE TITLE
[Suggestion] 1.20

### ISSUE THREAD

**Issue by ClayCoffee** [LoneDev6/ServerBooster#75] opened 2023-06-21 10:34 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LoneDev6** [comment] 2023-06-21 13:35
Duplicate of https://github.com/PluginBugs/Issues-ServerBooster/issues/74

**Closed as not planned by LoneDev6** 2023-06-21 13:35 UTC
Labels: duplicate
